name: ci

on:
  push:
    branches: [extra-credit]
  pull_request:
    branches: [main]

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: pnpm install --include=dev
      - run: pnpm run test
