name: ci

on:
  push:
    branches: [extra-credit]
  pull_request:
    branches: [main]

jobs:
  setup_pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.12.2

      - name: Install dependencies
        run: pnpm install

      - name: run Vitest
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - run: pnpm run test
